on: push
jobs:
  main:
    name: Build and test
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v2  
        with:
          node-version: 12
      - run: npm ci
      - run: npm test   
